<a href="https://colab.research.google.com/github/coolksrini/edureka_python_course/blob/main/Assignment_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 1. Convert the given list into a numpy array and replace the odd elements with -2.
Lst=[[1,2,3], [4,5,6], [7,8,9]]

In [10]:
import numpy as np

Lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(Lst)
arr[arr % 2 != 0] = -2
print(arr)

[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


## 2. In the numpy array given below print all the elements ranging from 8 to 15.
arr = [1,2,3,4,5,8,9,10,12,22,32,54,99,6,7]

In [11]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7])
print(arr[(arr >= 8) & (arr <= 15)])

[ 8  9 10 12]


## 3. Create a 3*3 narray that includes numbers from 1 to 9 and swap columns 1 and 2.

In [12]:
import numpy as np

arr = np.arange(1, 10).reshape(3, 3)
print("Original array:")
print(arr)

# Swap columns 1 and 2 (0-indexed)
arr[:, [0, 1]] = arr[:, [1, 0]]

print("\nArray after swapping columns 1 and 2:")
print(arr)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array after swapping columns 1 and 2:
[[2 1 3]
 [5 4 6]
 [8 7 9]]


## 4. In the given numpy array replace the NaN values with the average of columns:
arr= np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])

In [13]:
import numpy as np

arr = np.array([[1.3, 2.5, 3.6, np.nan], [2.6, 3.3, np.nan, 5.5], [2.1, 3.2, 5.4, 6.5]])

# Calculate the mean of each column, ignoring NaN values
col_means = np.nanmean(arr, axis=0)

# Find indices where the array has NaN values
nan_indices = np.isnan(arr)

# Replace NaN values with the corresponding column mean
arr[nan_indices] = col_means[np.where(nan_indices)[1]]

print(arr)

[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


## 5. For the numpy array given below perform the following operation:
i. Convert the numpy array into a numpy matrix

ii. Sort the values in a matrix

arr = [[2,4,6],[1,3,5]]

In [16]:
import numpy as np

arr = np.array([[2, 4, 6], [1, 3, 5]])

# Convert the numpy array into a numpy matrix
matrix = np.asmatrix(arr)
print("Matrix:")
print(matrix)

# Sort the values in the matrix (sorts in-place)
matrix.sort()

print("\nSorted matrix:")
print(matrix)

Matrix:
[[2 4 6]
 [1 3 5]]

Sorted matrix:
[[2 4 6]
 [1 3 5]]
